build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.20"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20"
labels:
  org.opencontainers.image.title: "TIS: setup"
  org.opencontainers.image.description: "Setup Tis"
  org.opencontainers.image.source: "https://github.com/Tis-Control-HA/get-tis"
  org.opencontainers.image.licenses: "MIT License"
